import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FDF8EC',
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 40,
    paddingBottom: 60,
    justifyContent: 'center',
  },
  topDecoration: {
    position: 'absolute',
    top: -30,
    left: -30,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#F7C942',
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  logoCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#1E1E1E',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    overflow: 'hidden',
  },
  logoImage: {
    width: 50,
    height: 50,
  },
  titulo: {
    fontSize: 26,
    fontWeight: '900',
    color: '#1A1A1A',
    letterSpacing: 1,
  },
  subtitulo: {
    fontSize: 13,
    color: '#777',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 18,
  },
  formContainer: {
    width: '100%',
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: '#333',
    marginBottom: 6,
    marginTop: 10,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E2E2',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
  },
  btnPrimary: {
    backgroundColor: '#F58220',
    borderRadius: 25,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 16,
    elevation: 3,
  },
  btnPrimaryText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 18,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#333333',
  },
  dividerText: {
    marginHorizontal: 10,
    fontSize: 12,
    color: '#666',
  },
  btnDriver: {
    alignItems: 'center',
    marginBottom: 10,
  },
  btnDriverText: {
    fontSize: 14,
    color: '#555',
    textDecorationLine: 'underline',
    fontWeight: '500',
  },
  footerContainer: {
    alignItems: 'center',
    marginTop: 25,
  },
  forgotText: {
    color: '#2A75D3',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 12,
  },
  registerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  registerText: {
    fontSize: 13,
    color: '#555',
  },
  registerLink: {
    fontSize: 13,
    color: '#555',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  homeLink: {
    fontSize: 12,
    color: '#888',
  },
  bottomDecorationContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 140,
    height: 140,
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  bottomYellow: {
    position: 'absolute',
    bottom: -20,
    right: -20,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#F7C942',
  },
  bottomOrange: {
    position: 'absolute',
    bottom: -40,
    right: -10,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#F58220',
  },
});